version: '2'
services:
  hadoop:
    container_name: hadoop
    hostname: hadoop
    build: hadoop
    restart: always
    expose:
      - "9000"
    ports:
      - "9000:9000"

  hbase:
    depends_on:
      - hadoop
      - zoo1
      - zoo2
      - zoo3
    container_name: hbase
    hostname: hbase
    build: hbase
    restart: always
    links:
      - hadoop
      - zoo1
      - zoo2
      - zoo3
    expose:
      - "16010"
      - "16201"
      - "16301"
    ports:
      - "16010:16010"
      - "16201:16201"
      - "16301:16301"
    environment:
      HADOOP_HOSTNAME: hadoop

  zoo1:
    container_name: zoo1
    hostname: zoo1
    image: zookeeper
    restart: always
    ports:
        - 2181:2181
    environment:
        ZOO_MY_ID: 1
        ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo2:
    container_name: zoo2
    hostname: zoo2
    image: zookeeper
    restart: always
    ports:
        - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo3:
    container_name: zoo3
    hostname: zoo3
    image: zookeeper
    restart: always
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  pinpoint-collector:
    depends_on:
      - hbase
    container_name: pinpoint-collector
    hostname: collector
    build: pinpoint-collector
    restart: always
    expose:
      - "9994"
      - "9995"
      - "9996"
    ports:
      - "9994:9994"
      - "9995:9995/tcp"
      - "9996:9996/tcp"
      - "9995:9995/udp"
      - "9996:9996/udp"
    links:
      - hbase
      - zoo1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://hbase:16010/table.jsp?name=TraceV2"]
      interval: 10s
      timeout: 5s
      retries: 5

  pinpoint-web:
    depends_on:
      - hbase
      - pinpoint-collector
    container_name: pinpoint-web
    hostname: web
    build: pinpoint-web
    restart: always
    expose:
      - "8080"
    ports:
      - "3080:8080"
    links:
      - hbase
      - zoo1
